// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emxtnhrtkgibxlmnvgra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVteHRuaHJ0a2dpYnhsbW52Z3JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5OTA5NjEsImV4cCI6MjA1MjU2Njk2MX0.k-YIgmvhqlH5Hk1S8lZ4IxWhJh9k9XbOq3s2jknhyJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);